[package]
name = "state"
version = "0.1.0"
edition = "2021"

[dependencies]
tui = { path = "../tui" }
config = { path = "../config" }
utils = { path = "../utils" }
anyhow = { workspace = true}
notify = "7.0.0"
