# This is an example for the local config.
# Serde maps each key from the `.toml` file to the fields
# of the `BlinkConfig` struct.
#
# This is hot-reloadable.
message = "hi from the config"

[local_requests]
requests = [
    { name = "Get Users", url = "http://example.com/api/users", body = "", method = "GET" },
    { name = "Create User", url = "http://example.com/api/users", body = "{ \"name\": \"John Doe\" }", method = "POST" },
    { name = "Delete User", url = "http://example.com/api/users/1", body = "", method = "DELETE" },
]

# Example of keybinding remapping.
[[keybindings]]
key = "b"
modifiers = ["Control"]
command = "MoveCursorLeft"

[[keybindings]]
key = "f"
modifiers = ["Control"]
command = "MoveCursorRight"

[[keybindings]]
key = "c"
modifiers = ["Control"]
command = "Quit"
