[package]
name = "blink"
version = "0.1.0"
edition = "2021"

[dependencies]
state = { path = "../state" }
utils = { path = "../utils" }
config = { path = "../config" }
anyhow = { workspace = true }
clap = { version = "4.5.21", features = ["derive"] }
