[package]
name = "tui"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.29.0"
crossterm = "0.28.1"
anyhow = { workspace = true }
config = { path = "../config" }
utils = { path = "../utils" }
ropey = "1.6.1"
